/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import com.google.inject.Guice;
import com.google.inject.Injector;

public class App {

    public static void main(String[] args) {

        Injector injector = Guice.createInjector(new DrawSquareModule());
        DrawSquareRequest request = injector.getInstance(DrawSquareRequest.class);

        // DrawSquareRequest request = new DrawSquareRequest(drawSquare);
        request.drawSquare.draw();
    }
}
