/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import com.google.inject.Guice;
import com.google.inject.Injector;

public class App {

    public static void main(String[] args) {

        Injector injector = Guice.createInjector(new DrawSquareModule());
        DrawShape drawSquare = injector.getInstance(DrawSquare.class);

        DrawSquare square = new DrawSquare(drawSquare);
        square.draw();
    }
}
